### ISSUE TITLE
All your robots belong to us!

### ISSUE THREAD

**Issue by dellaert** [borglab/GTDynamics#281] opened 2021-09-24 14:07 UTC
Can we get the legged sdfs from the subT challenge to load?
https://github.com/osrf/subt/wiki/Robots

**Comment by varunagrawal** [comment] 2021-09-25 21:06
You mean "All your robots ARE belong to us!"? 😉 

It should be very doable.

**Comment by varunagrawal** [comment] 2021-09-27 13:08
Here's the `cerberus_anymal_b_sensor_config_1` from the above repo.

![cerberus_anymal_b](https://user-images.githubusercontent.com/975964/134914469-3442308c-3b1d-4da8-9575-32fe001eb10f.png)

**Comment by dellaert** [comment] 2021-09-27 14:34
Cool. PR for this? BTW #253 does not seem to work with our Docker images, says @nrakoski3 . Can you try it inside Docker? Did I not install SDF correctly?

**Comment by varunagrawal** [comment] 2021-09-27 15:13
What's the error message? That it doesn't work doesn't help me at all :)

**Comment by varunagrawal** [comment] 2021-09-27 15:47
I know what the problem is: @nrakoski3 waited too long to try it.

So the PR to get rid of `wTcom` landed but `roboplot` doesn't have that updated yet. I believe this happened somewhere in this past week since I was able to plot the NAO when I created that PR. I'll push an update to roboplot and this should work.

**Comment by varunagrawal** [comment] 2021-09-27 16:03
Okay, the plotting now works even in the docker image.

**Closed** 2021-11-03 23:38 UTC
